Rest api
NSU-21211/RiverKnowledgeBase-backend pull request #5
Opened 2024-03-27 08:22 UTC by vitalioo

2024-03-27 14:13 UTC, murloteg requested changes

2024-03-27 14:13 UTC, murloteg commented on hs_err_pid22816.log
Почему это попало в коммит?

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/dto/RiverDTO.java
> +    String label;
почему package-private видимость полей?
сделай private

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/entity/RiverEntity.java
> +    URI riverLink;
почему package-private видимость полей?
сделай private

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/entity/RiverEntity.java
> +    public RiverEntity() {
зачем отдельный конструктор для инициализации коллекций?
почему бы не сделать инициализацию при объявлении?

ex: Set<String> origin = new HashSet<>();

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/parser/impl/CountryAndMouthParser.java
> +        return "country-mouth";
надо вынести все эти конфигурационные штуки в application.properties

а сюда инжектить через @Value

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/parser/impl/ImageAndTributariesParser.java
> +        return "image-tributaries";
аналогичное замечание про аннотацию Value

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/parser/impl/LengthAndOriginParser.java
> +        return "length-origin";
аналогичное замечание про аннотацию Value

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/parser/impl/URIAndLabelParser.java
> +        return "uri-label";
аналогичное замечание про аннотацию Value

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/parser/impl/WatershedAndLocatedParser.java
> +        return "watershed-located";
аналогичное замечание про аннотацию Value

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/query/impl/CountryAndMouthWikidataQuery.java
> +        return "country-mouth";
аналогичное замечание про аннотацию Value

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/query/impl/ImageAndTributariesWikidataQuery.java
> +        return "image-tributaries";
аналогичное замечание про аннотацию Value

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/query/impl/LengthAndOriginWikidataQuery.java
> +        return "length-origin";
аналогичное замечание про аннотацию Value

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/query/impl/RiverURIAndLabelQuery.java
> +        return "uri-label";
аналогичное замечание про аннотацию Value

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/query/impl/WatershedAndLocatedWikidataQuery.java
> +        return "watershed-located";
аналогичное замечание про аннотацию Value

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/service/query/QueryService.java
> +    CompletableFuture<Void> executeQuery(String riverName, Map<RiverPairKey, RiverEntity> rivers, WikidataQuery query);
действительно ли нужно возвращать CompletableFuture из метода? Или можно обойтись тут void?

правильного ответа может не быть)

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/service/query/impl/QueryServiceImpl.java
> +            throw new RuntimeException(e);
сделай кастомный runtime-exception

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/service/query/impl/QueryServiceImpl.java
> +                e.printStackTrace();
дорого по ресурсам может быть так щедро stack-trace'ами разбрасываться

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/service/query/impl/QueryServiceImpl.java
> +                throw new RuntimeException(e);
кастомный эксепшн

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/service/query/impl/QueryServiceImpl.java
> +                if (parser.isPresent()) {
попробуй тут stream api использовать, чтобы не было этой кучи вложенных if-ов
как минимум: ifPresentOrThrow

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/service/river/impl/RiverServiceImpl.java
> +        CompletableFuture<Void> allDone = CompletableFuture.allOf(futures.toArray(new CompletableFuture[0]));
нельзя тут через for-each пройтись и у каждого позвать join, чтобы не кастовать массив?

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/util/RiverPairKey.java
> +    URI link;
private видимость

2024-03-27 14:13 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/util/RiverPairKey.java
> +    public boolean equals(Object o) {
Посмотри на аннотацию @EqualsAndHashCode
можно ли ее тут применить вместо этих методов

2024-03-28 08:43 UTC, vitalioo commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/service/query/QueryService.java
> +    CompletableFuture<Void> executeQuery(String riverName, Map<RiverPairKey, RiverEntity> rivers, WikidataQuery query);
Да, нужно CompletableFuture, чтобы в сервисе дождаться выполнения всех запросов и вернуть в контроллер данные

2024-03-29 02:57 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/service/query/QueryService.java
> +    CompletableFuture<Void> executeQuery(String riverName, Map<RiverPairKey, RiverEntity> rivers, WikidataQuery query);
`CompletableFuture` тут к месту, потому что это дейставительно асинхронный запрос. А вот что, что это `CompletableFuture<Void>` несколько смущает. Как пользователь этого метода, я бы ожидал что-то типа
`CompletableFuture<Map<RiverPairKey, RiverEntity>> executeQuery(String riverName, WikidataQuery query);`

2024-03-29 03:41 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/query/impl/LengthAndOriginWikidataQuery.java
> +                  FILTER (STRSTARTS(?label, "%s")).
Фильрация по имени, скорее всего, неэффективна. Лучше использовать в качестве первичного ключа wikidata id и выбирать объекты по нему.

2024-03-29 03:44 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/service/query/impl/QueryServiceImpl.java
> +                parser.parse(resultModel, rivers);
Изменяемые аргументы функции это довольно плохой дизайн. Это уже не чистая функия, значит ее будет неудобно тестировать, закрывать mock объектами и переиспользовать.

2024-03-29 03:48 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/service/query/impl/QueryServiceImpl.java
> +            log.error("Error executing request SPARQL: {}", (Object) e.getSuppressed());
В этом месте теряется стектерйс. В проде такие вещи сильно затрудняют отладку, поэтом нужно либо пробрасывать исключение выше обернув его в собственное исключение
```throw new SparqlQueryException("Unable to find rivers by name in WikiData", e);```
либо логгировать исключение вместе со стектрейсом
```log.error("Error executing request SPARQL: {}", e.getSuppressed(), e)```

2024-03-29 03:53 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/dto/RiverDTO.java
> +    @Schema(description = "Длина реки")
Для числовых единиц лучше указывать единицу измерения в Swagger. А еще лучше указывать ее прямо в имени переменной, это сделает код самоочевидным и пользователям API не придется уточнять месантику переменной по документации. `private Integer lengthKm`

2024-03-29 04:11 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/entity/RiverEntity.java
> +    @Schema(description = "Изображение реки")
Хорошо бы добавить required, потому что часть полей явно обязательные, а часть опциональные.

2024-03-29 04:14 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/entity/RiverEntity.java
> +    private String country;
Что будет если стран несколько? Например: https://www.wikidata.org/wiki/Q82776

2024-03-29 06:58 UTC, vitalioo commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/entity/RiverEntity.java
> +    private String country;
Думал, что не будем пока с граничащими реками работать, добавлю

2024-03-29 08:51 UTC, vitalioo commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/query/impl/LengthAndOriginWikidataQuery.java
> +                  FILTER (STRSTARTS(?label, "%s")).
Проблема может быть в том, что если искать по wikidata id, можно получить не ту реку которую бы хотел пользователь, вот пример
![image](https://github.com/NSU-21211/RiverKnowledgeBase-backend/assets/112821362/9f65000b-3a9c-4c89-acd2-2d12f4cfabf9)
Wikidata выдаёт такие реки по запросу на реку Енисей

2024-03-31 07:12 UTC, murloteg requested changes

2024-03-31 07:12 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/util/RiverPairKey.java
>  public class RiverPairKey {
почему этот класс находится в пакете util?
Он точно должен лежать в model.wikidata, так как тесно связан с параметрами Wikidata

2024-03-31 07:12 UTC, murloteg commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/service/query/impl/QueryServiceImpl.java
> +                parser.ifPresentOrElse(p -> {
строчка Optional<WikidataResponseParser> parser = getParserByType(query.getType()); лишняя

можно сразу от метода getParserByType(query.getType()) вызывать ifPresentOr...

И здесь ifPresentOrElse не подходит.
Ведь если парсер не нашелся по типу запроса, то что-то явно пошло не так (сущности то связаны между собой), нужно бросать exception, а не просто писать лог.

так что используй тут конкретно ifPresentOrThrow

2024-03-31 07:18 UTC, murloteg commented on build.gradle
> +	/*s pringdoc-openapi */
и это что за коммент странный

2024-03-31 07:21 UTC, murloteg commented on gradle.properties
> +openAPIVersion=1.8.0
лишняя зависимость, убери

2024-03-31 07:21 UTC, murloteg commented on build.gradle
> +	id 'org.springdoc.openapi-gradle-plugin' version "$openAPIVersion"
лишняя зависимость, убери

2024-04-07 09:28 UTC, murloteg commented on build.gradle
зависимость на Thymeleaf больше не нужна

2024-04-07 09:28 UTC, murloteg commented on src/main/resources/application.properties
spring.data.mongodb.auto-index-creation=true

иначе не будет создаться индекс для label

2024-04-07 12:41 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/controller/RiverController.java
> +                                @NotNull @NotBlank @Length(min = 2) String riverId) {
Так `name` или `riverId`?

2024-04-07 13:43 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/factory/impl/WikidataParserFactoryImpl.java
> +        return switch (type) {
Возможно, есть смысл использовать enum вместо string. Строковые аргументы, которые могут содержать лишь какие-тио определенные значения довольно сложно потом поддерживать. Клиенты, который вызывает метод, нужно каким-то образом догадаться какие значения допустимы, а какие нет.

2024-04-07 13:43 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/dto/RiverDTO.java
> +@Document(collection = "riverDTOs")
Смешивать модель данных, которая лежит в БД c моделью, которая предатеся через API не очень хорошая идея. Все, что лежит в базе потенциально лежит там вечно и если будущем потрбуется изменить API, придется делать миграцию БД.

2024-04-07 13:43 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/parser/impl/ImageAndTributariesParser.java
> +            URI image = URI.create(String.valueOf(resultModel.getRows().get(0).get("image")));
Что будет если `resultModel.getRows()` будет содержать больше одной записи? Здесь явно не хватает проверки на то, что SPARQL запрос вернул ожидаемые данные.

2024-04-07 13:43 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/parser/impl/MainRiverInfoParser.java
> +            String riverId = riverLink.substring(riverLink.lastIndexOf("/") + 1);
Лучше парсинг WikidataID из URL вынести в отдельный статический метод и проверять что это действительтно WikidataID, а не что-то еще.

2024-04-07 13:43 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/parser/impl/MainRiverInfoParser.java
> +        for (int i = 0; i < resultModel.getRowCount(); ++i) {
Почему бы не использовать foreach?

2024-04-07 13:43 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/parser/impl/MainRiverInfoParser.java
> +                river.setAdministrativeTerritorials(new HashSet<>(List.of(territorials)));
А почему не `Set.of`?

2024-04-07 13:43 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/service/query/impl/QueryServiceImpl.java
> +            log.info("Запрос " + query.getType() + " для реки " + name + " выполнен. Количество строк запроса = " + resultModel.getRowCount());
Уровни логгирования довольно странные. Вот неплохая статься о том как выбирать уровень логгирования: https://blog.datalust.co/choosing-the-right-log-levels/

2024-04-07 13:43 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/service/query/impl/QueryServiceImpl.java
> +                throw new SparqlQueryException("Нет реки с id: " + riverId, e);
Сообщение об ошибке вводит в заблуждение. `SparqlClientException` может быть выброшен по разным причинам

2024-04-07 13:43 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/service/query/impl/QueryServiceImpl.java
> +        return CompletableFuture.supplyAsync(() -> {
Здесь напрашивается `ThreadPool` иначе количество одновременных запросов ничем не будет ограничено

2024-04-07 13:43 UTC, Miroff commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/repository/RiverRepository.java
> +public interface RiverRepository extends MongoRepository<RiverDTO, String> {
Не вижу имплементации этого интерфейса

2024-04-08 13:19 UTC, vitalioo commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/parser/impl/ImageAndTributariesParser.java
> +            URI image = URI.create(String.valueOf(resultModel.getRows().get(0).get("image")));
resultModel.getRows() и будет содержать больше одной записи, однако поскольку запрос идёт по Wikidata id, то в resultModel будут лежать строки рек с разным названием, но с одинаковым id и одинаковыми запрашиваемыми данными, поэтому исхода лишь два: либо запрашиваемые данные будут = null, т.е. их отсутствие, либо же они будут и их можно получить по первому же индексу

2024-04-08 14:32 UTC, vitalioo commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/model/wikidata/parser/impl/MainRiverInfoParser.java
> +                river.setAdministrativeTerritorials(new HashSet<>(List.of(territorials)));
Если будет Set.of то вызовется IllegalArgumentException на примере:
![image](https://github.com/NSU-21211/RiverKnowledgeBase-backend/assets/112821362/594f89c5-14d2-4db6-aa90-092cca963124)
Если сделать List.of а после new HashSet, то повторений не будет

2024-04-08 14:36 UTC, vitalioo commented on src/main/java/nsu/ccfit/ru/upprpo/riverknowledge/repository/RiverRepository.java
> +public interface RiverRepository extends MongoRepository<RiverDTO, String> {
В имплементации нет надобности поскольку spring data jpa самостоятельно выполняет запросы к базе данных по определению метода

2024-04-14 09:53 UTC, murloteg approved these changes

2024-04-14 09:53 UTC, merged